// Generated by CoffeeScript 1.8.0
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

window.Hand = (function(_super) {
  __extends(Hand, _super);

  function Hand() {
    return Hand.__super__.constructor.apply(this, arguments);
  }

  Hand.prototype.model = Card;

  Hand.prototype.initialize = function(array, deck, isDealer) {
    this.deck = deck;
    this.isDealer = isDealer;
  };

  Hand.prototype.hit = function() {
    while (this.scores()[0] < 17) {
      this.at(0).flip();
      this.hit();
    }
    this.add(this.deck.pop()).last();
    if (this.scores()[0] > 17 && this.scores()[0] < 21) {
      return this.trigger('stand');
    }
  };

  Hand.prototype.scores = function() {
    var hasAce, score;
    hasAce = this.reduce(function(memo, card) {
      return memo || card.get('value') === 1;
    }, false);
    score = this.reduce(function(score, card) {
      return score + (card.get('revealed') ? card.get('value') : 0);
    }, 0);
    if (hasAce) {
      return [score, score + 10];
    } else {
      return [score];
    }
  };

  Hand.prototype.stand = function() {
    return this.trigger('stand');
  };

  Hand.prototype.busted = function() {
    if (this.scores()[0] > 21) {
      return this.trigger(console.log('You are busted'));
    }
  };

  Hand.prototype.blackJack = function() {
    if (this.scores()[0] = 21) {
      return this.trigger(console.log('Black Jack!'));
    }
  };

  return Hand;

})(Backbone.Collection);
